### ISSUE TITLE
Backward compatibility 

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#102]
Per JJ:

Our principle is that all versions of our R wrapper packages should work with the current TF version (dev master if possible) as well as all previous versions back to some threshold. For example, the tensorflow package works on all versions of tensorflow back to v1.0 and the Keras package works on all versions of Keras from 2.0.8 all the way back to 2.0.0. If we don't do this it becomes very awkward for both devs and end users (as we are now experiencing with tfestimators).

The keras package has many examples of how to support newer versions while still not failing against older version. In your example of an argument being added, we simply switch our calling semantics to `do.call` and conditionally include the new argument. For example here (https://github.com/rstudio/keras/blob/master/R/model.R#L613-L625):

```r
predict_generator <- function(object, generator, steps, max_queue_size = 10, verbose = 0) {
  
  args <- list(
    generator = generator,
    steps = as.integer(steps),
    max_queue_size = as.integer(max_queue_size)
  )
  
  if (keras_version() >= "2.0.1")
    args$verbose <- as.integer(verbose)
  
  call_generator_function(object$predict_generator, args)
}
```

In this case I am silently ignore the argument in earlier versions. This might be okay or we depending on what the argument is you might want to checking for `!missing` and issue a warning. 

You could also have functions which bomb out entirely if the right version isn't available. The main idea is that given the way the R package system works (users tend to get forced to the latest version by CRAN + availability of bug fixes) we can't afford to tie our R package versions to the latest Python package versions.

I had assumed that the reason for our v1.3.0 branch was some fundamental incompatibility with TF v1.4. If however the only concern is new arguments or some functions that require TF v1.4 we should just add the conditional code like that above required to enable everyone to develop on and use the master branch.

**Comment by terrytangyuan** [comment]
@jjallaire I am trying to work on this issue [here](https://github.com/rstudio/tfestimators/commit/ef06e7e7ca6ce7f163f54da674d5a83ea974e0fd) and getting the following error: 
```
Unable to convert R object to Python type
```
Is there anything I am missing that I could borrow from Keras?

**Comment by jjallaire** [comment]
It would be good to narrow down where exactly the error is coming from. Could you figure out exactly what triggers the error? Could it be something coming from `...` ?

**Comment by terrytangyuan** [comment]
Do you have any suggestions on how to narrow this down? I tried to remove `...` but it gives the same error happening in `do.call()`. Here is the stacktrace if it's useful:

```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Unable to convert R object to Python type 
14.
stop(structure(list(message = "Unable to convert R object to Python type", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("1   reticulate.so                       0x0000000109084cb9 _ZN4Rcpp9exceptionC2EPKcb + 185", 
    "2   reticulate.so                       0x0000000109084b40 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 48",  ... 
13.
py_call_impl(callable, dots$args, dots$keywords) 
12.
(structure(function (...) 
{
    dots <- py_resolve_dots(list(...))
    result <- py_call_impl(callable, dots$args, dots$keywords) ... 
11.
do.call(object$estimator$train, args) at tf_estimator.R#103
10.
train.tf_estimator(., input_fn = specs$input_fn) at generic_methods.R#10
9.
train(., input_fn = specs$input_fn) 
```

**Comment by jjallaire** [comment]
Maybe look at the types of all of the args before you pass them in to see if anything looks non-convertable? I can pull down this branch and take a closer look in the morning.

**Comment by terrytangyuan** [comment]
Thanks for the suggestions! I think I just figured it out - I passed unnecessary items to `args` that doesn't work with `object$estimator$train`!

**Comment by jjallaire** [comment]
Excellent, glad you figured it out!

On Tue, Oct 10, 2017 at 9:43 PM, Yuan (Terry) Tang <notifications@github.com
