### ISSUE TITLE
Error when using initializable iterator with estimator

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/tfestimators#110]
Motivation: we want to be able to use a hash table to map string labels to integers on the fly when using the datasets API. This requires using `make_initializable_iterator()` instead of `make_one_shot_iterator()` at https://github.com/rstudio/tfdatasets/blob/master/R/dataset_iterators.R#L72. See e.g. https://stackoverflow.com/questions/44374083/tensorflow-cannot-capture-a-stateful-node-by-value-in-tf-contrib-data-api and https://stackoverflow.com/questions/44519045/new-dataset-map-transformation-and-lookup-table-incompatible-string-type. However, after making the change, the simple example below breaks.

MRE:

```
library(tfestimators)
library(tfdatasets)
file_path <- "data/iris.csv" # https://github.com/rstudio/tfdatasets/blob/master/tests/testthat/data/iris.csv
iris_spec <- csv_record_spec(file_path)

dataset <- text_line_dataset(file_path, record_spec = iris_spec) %>%
  # dataset_map(function(record) {
  #   record$Species <- record$Species - 1L
  #   record
  # }) %>%
  dataset_batch(25)

cols <- feature_columns(
  column_numeric("Petal.Width", "Petal.Length")
)
model <- dnn_classifier(
  feature_columns = cols,
  hidden_units = c(20, 20))
model %>%
  train(input_fn(dataset, features = c(Petal.Length, Petal.Width), response = "Species"))
```

Error:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: ValueError: Tensor("MapDataset_8:0", shape=(), dtype=variant) must be from the same graph as Tensor("Iterator:0", shape=(), dtype=resource, device=/device:CPU:0)..
```
Note we're expecting another error here (`Label IDs must < n_classes`) but the error is raised at the iterator instantiation. Also note that no hash tables are in this example since the error occurs without them.

@terrytangyuan Any ideas?

**Comment by kevinykuo** [comment]
Actually, this isn't a great example since the classifiers in `estimators` have a `label_vocabulary` argument. We might not run into this issue with the keras API. Let me experiment a bit and report back. We might not have a problem at all.

**Comment by terrytangyuan** [comment]
Yes, you should really take advantage of `label_vocabulary`. I am not sure what the problem is on top of my head but it would be great if you could make a minimal reproducible Python code to see if this is something on R end or not.
