### ISSUE TITLE
export_savedmodel crashing with dnn_linear_combined_classifier

### ISSUE THREAD

**Issue by lukasthaler** [rstudio/tfestimators#115]
Long story short: i built a dnn_linear_combined_classfier and trained it, which went perfectly fine. When I wanted to serialize it to disk using export_savedmodel( ), it failed with an error.

Here's the error and traceback (wad_classifier is my dnn_linear_combined_classifier)

` > export_savedmodel(wad_classifier)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'NoneType' object is not iterable

Detailed traceback: 
  File "/my-home-path/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/estimator/canned/parsing_utils.py", line 273, in regressor_parse_example_spec
    parsing_spec = fc.make_parse_example_spec(feature_columns)
  File "/my-home-path/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/feature_column/feature_column.py", line 425, in make_parse_example_spec
    for column in feature_columns: `

I suspect the following: the traceback shows that an iteration over feature_columns is attempted and fails with a TypeError. I did some research and found out that 'NoneType' is the data type for empty (NULL or None, depending on which language you want to use) entries. This makes perfect sense, since dnn_linear_combined_classifier does not take 'feature_columns' as an argument but rather 'dnn_feature_columns' and 'linear_feature_columns', so the feature_columns-argument will obviously be a NULL, thus causing the error.

Best regards

**Comment by jjallaire** [comment]
@javierluraschi Could you take a look at this?

**Comment by terrytangyuan** [comment]
@lukasthaler Thanks for reporting! Just fixed this in master. Could you try again?

**Comment by lukasthaler** [comment]
@terrytangyuan exporting works like a charm now, thanks!

But, without having made any changes to my code, I am getting an unused argument error now when trying to call predict( ) with my classifier:

> wad_classifier %>% predict(input_fn = wad_pred_input_fn(wad_test_data))
Error in predict(., input_fn = wad_pred_input_fn(wad_test_data)) : 
  unused argument (input_fn = wad_pred_input_fn(wad_test_data))

Oddly enough, calls to evaluate( ) still work without any issues. Is there any chance that this issue is related to the fix?

**Comment by terrytangyuan** [comment]
Could you share a detailed error with stack trace?

**Comment by lukasthaler** [comment]
Here's the information traceback( ) returns:

> wad_classifier %>% predict(input_fn = wad_pred_input_fn(wad_test_data))
Error in predict(., input_fn = wad_pred_input_fn(wad_test_data)) : 
  unused argument (input_fn = wad_pred_input_fn(wad_test_data))
> traceback()
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: wad_classifier %>% predict(input_fn = wad_pred_input_fn(wad_test_data))

Fyi: the code tags in the above error messages are unintentional, they are part of the traceback result

**Comment by terrytangyuan** [comment]
I don't see how this error is related to the change I made. It would be better if you could share a minimal reproducible example and file a separate issue. Thanks!

**Comment by lukasthaler** [comment]
I just did in #116
