### ISSUE TITLE
dnn_linear_combined_classifier prediction fails with unused argument error

### ISSUE THREAD

**Issue by lukasthaler** [rstudio/tfestimators#116]
The issue is pretty straightforward: my instances of a dnn_linear_combined_classifier won't predict anything, failing with an unused argument exception. Below I provide a minimal example that generates the error as well as the error message and the traceback. I am using RStudio ver 99.9.9 and python 2.7. The `tfestimators` package is on the latest version, I reinstalled it just today

```
>library(tfestimators)
# generate random data
data = data.frame(
dnn_1 = rnorm(1000),
dnn_2 = rnorm(1000,mean=2,sd=0.2),
dnn_3 = rnorm(1000,mean=-1,sd=5),
lin_1 = 0.01*(1:1000)+rnorm(1000,sd=0.01),
lin_2 = 0.1*(1000:1)+rnorm(1000,sd=0.1),
label = as.integer(sample(c(0,1,2),1000,replace=T)))

index = sample(1000,700)
train_data = data[index,]
train_label = data$label[index]
pred_data = data[-index,]

# input functions
feats = names(data)[1:5]

train_input_fn = function(data) {
  input_fn(data,
           features = feats,
           response = "label",)
}
pred_input_fn = function(data) {
  input_fn(data,
           features = feats)
}

# feature columns
lin_feats = feature_columns(column_numeric(feats[4:5]))
dnn_feats = feature_columns(column_numeric(feats[1:3]))

# classifier
dnn_lin_classifier = dnn_linear_combined_classifier(
  linear_feature_columns = lin_feats,
  dnn_feature_columns = dnn_feats,
  dnn_hidden_units = c(15,5),
  dnn_optimizer = 'RMSProp',
  n_classes = 3
)

# training
dnn_lin_classifier %>% train(input_fn = train_input_fn(train_data))

# predicting some data - error occurs here
dnn_lin_classifier %>% predict(input_fn = pred_input_fn(pred_data))
```

The last call results in the following error message:
```
> dnn_lin_classifier %>% predict(input_fn = pred_input_fn(pred_data))
Error in predict(., input_fn = pred_input_fn(pred_data)) : 
  unused argument (input_fn = pred_input_fn(pred_data))
```

Here's the traceback for some additional information that might be valuable:
```
> traceback()
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: dnn_lin_classifier %>% predict(input_fn = pred_input_fn(pred_data))
```

@terrytangyuan I suppose you would want to be notified, if I am wrong pardon the mention :-)

Best regards

**Comment by terrytangyuan** [comment]
I wasn't able to reproduce the issue. What version of TF have you installed, e.g. `tensorflow::tf_config()`?

**Comment by lukasthaler** [comment]
It seems there is something wrong with my tensorflow. I removed everything and am currently trying to reinstall, but I am meeting unexpected errors. I will get back to this once i successfully get an installation up and running

**Comment by lukasthaler** [comment]
Okay, a fresh installation of tensorflow did the trick. Everything is working fine now. Still bugs me what exactly caused the error, but it was within the tf installation

**Comment by terrytangyuan** [comment]
Great. Thanks!
