### ISSUE TITLE
Wide and Deep Tutorial - ValueError: Column dtype and SparseTensors dtype must be compatible

### ISSUE THREAD

**Issue by MartinGeierino** [rstudio/tfestimators#118]
Hi,

I've tried the wide and deep tutorial from: https://tensorflow.rstudio.com/tfestimators/articles/examples/wide_and_deep.html

I didn't make any changes to the code and it runs fine until line:
`train(model, input_fn = train_input_fn, steps = 2)`

This line throws following error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : ValueError: Column dtype and SparseTensors dtype must be compatible. key: education, column dtype: <dtype: 'string'>, tensor dtype: <dtype: 'int32'>
> 
> 7.
> stop(structure(list(message = "ValueError: Column dtype and SparseTensors dtype must be compatible. key: education, column dtype: <dtype: 'string'>, tensor dtype: <dtype: 'int32'>", call = py_call_impl(callable, dots$args, dots$keywords), cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), .Names = c("file", "line", "stack"), class = "Rcpp_stack_trace")), .Names = c("message", ...
> 6.
> (structure(function (...) { dots <- py_resolve_dots(list(...)) result <- py_call_impl(callable, dots$args, dots$keywords) ...
> 5.
> do.call(object$estimator$train, args)
> 4.
> force(expr)
> 3.
> with_logging_verbosity(tf$logging$WARN, { do.call(object$estimator$train, args) })
> 2.
> train.tf_estimator(model, input_fn = train_input_fn, steps = 2)
> 1.train(model, input_fn = train_input_fn, steps = 2)

TF Config:
TensorFlow v1.3.0 (C:\Users\Martin\AppData\Local\conda\conda\envs\R-TENS~1\lib\site-packages\tensorflow)
Python v3.6 (C:\Users\Martin\AppData\Local\conda\conda\envs\r-tensorflow\python.exe)

**Comment by kevinykuo** [comment]
Will take a look!

**Comment by kevinykuo** [comment]
Issue was that we were reading in character columns as factors and passing those to feature columns that expect characters. PR with fix opened.

**Comment by terrytangyuan** [comment]
Great! That's quick!
