### ISSUE TITLE
Consider renaming or removing coef.tf_estimator()

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/tfestimators#121]
It returns trained weights so the name isn't great and I wonder how it's currently being used?

**Comment by jjallaire** [comment]
@terrytangyuan or @kevinushey can you provide some insight here?

**Comment by terrytangyuan** [comment]
There is now get_variable_name and get_variable_values in Python API (
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/estimator.py#L235).
I think we can rename it to variables()?

**Comment by terrytangyuan** [comment]
Or we can just provide wrappers for those two existing Python functions to
be consistent.

**Comment by kevinykuo** [comment]
I think a rename + refactor using the two methods mentioned above is appropriate. Will send a PR.

**Comment by kevinushey** [comment]
`coef()` seemed like the closest analogue in the set of `stats` generics but I agree that a separate name may be better.
