### ISSUE TITLE
Support for boosted trees estimators

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#146]
BoostedTreesClassifier and BoostedTreesRegressor are now indeed available in core [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/canned/boosted_trees.py).

@kevinykuo Let's use this issue to track progress since https://github.com/rstudio/tfestimators/issues/40 is only used for personal tracking of various upstream changes.

**Comment by kevinykuo** [comment]
Taking a stab at this.

**Comment by kevinykuo** [comment]
@terrytangyuan Currently I think there's a problem with the gradient calculation not liking integer labels. Here's the proposed fix https://github.com/tensorflow/tensorflow/compare/master...kevinykuo:bugfix/boosted-trees-labels-cast -- could you take a look to see if it makes sense? (Python noob here!)

**Comment by terrytangyuan** [comment]
The change looks good to me. Let's see if TF team has any comments on it (they may have some internal requirement regarding the performance).
