### ISSUE TITLE
Update site docs

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/tfestimators#153]

**Comment by kevinykuo** [comment]
@terrytangyuan how do I generate the references automatically?

**Comment by terrytangyuan** [comment]
You need to add it to the config here: https://github.com/rstudio/tfestimators/blob/master/pkgdown/_pkgdown.yml
and then do a `pkgdown::build_site(pathToPackage)`.

**Comment by jjallaire** [comment]
Actually, don't do the build_site (we take care of that separately when
building tensorflow.rstudio.com

On Fri, May 11, 2018 at 2:33 PM, Yuan (Terry) Tang <notifications@github.com

**Comment by terrytangyuan** [comment]
Oh right I kept forgetting that. We can just remove /docs folder altogether then.

**Comment by terrytangyuan** [comment]
Now that v1.9 is there. Could you add boosted trees estimators to the [API reference](https://tensorflow.rstudio.com/tfestimators/reference/)?
