### ISSUE TITLE
function reference typo in help page: *_column vs.  column_*

### ISSUE THREAD

**Issue by weirubin** [rstudio/tfestimators#157]
Should ***embedding_column***  be ***column_embedding***? https://github.com/rstudio/tfestimators/blob/f054d60d640c6cb2e2e0b547c2a13dc17bcc82eb/R/feature_columns.R#L228

Should ***categorical_column*** be ***column_categorical***?
https://github.com/rstudio/tfestimators/blob/f054d60d640c6cb2e2e0b547c2a13dc17bcc82eb/R/feature_columns.R#L189
https://github.com/rstudio/tfestimators/blob/f054d60d640c6cb2e2e0b547c2a13dc17bcc82eb/R/feature_columns.R#L227
https://github.com/rstudio/tfestimators/blob/f054d60d640c6cb2e2e0b547c2a13dc17bcc82eb/R/feature_columns.R#L231

Should ***crossed_column*** be ***column_crossed***?
https://github.com/rstudio/tfestimators/blob/f054d60d640c6cb2e2e0b547c2a13dc17bcc82eb/R/feature_columns.R#L231

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/rstudio/tfestimators/commit/c23bb1453ddb9357ec8f2c86fc7a52a78a2fd678
