### ISSUE TITLE
Environment variable issue (rlang , as_data_mask() deprecated)

### ISSUE THREAD

**Issue by baslia** [rstudio/tfestimators#159]
Hello,
with the update of rlang, there is an issue, I got a warning message:
The `parent` argument of `as_data_mask()` is deprecated.
Then when I use a named variable in the input_fn() from the tfestimators package, I got a message that says : _The parent argument in as_data_mask() is deprecated
The parent of the data mask is determined from either:
The env argument of eval_tidy()
Quosure environments when applicable_

I had to downgrade the rlang package to the version 0.2.2 as a fix, but it would be great to have a robust fix for that.
Thanks for helping.
Regards,
Adel

**Comment by kevinykuo** [comment]
Thanks for the report, the deprecation warnings will be addressed in the next update!

**Comment by jjallaire** [comment]
@kevinykuo Could you put together a PR for this?

**Comment by baslia** [comment]
Hi thanks,
does it mean that for the next update we can have the last version of rlang without an error when running the code ?
Thanks
Adel

**Comment by kevinykuo** [comment]
Looks like there's some issues beyond soft deprecating of functions. Investigating.

**Comment by kevinykuo** [comment]
@baslia this should be fixed on master now, I'll send a patch to CRAN today.

**Comment by baslia** [comment]
Thanks a lot for the fast great work !
