### ISSUE TITLE
Fix Travis status

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#33]
We need to start build against master version of TF so we should revisit to make Travis
working (for some reason I wasn't able to get the detailed error logs from
Travis long time ago).

Any help on this is appreciated.

**Comment by kevinushey** [comment]
Looks like we have Travis running now!

**Comment by terrytangyuan** [comment]
Yes! However, it takes 20 mins to run the tests, which may not be ideal. Any optimizations on this would be great.

**Comment by terrytangyuan** [comment]
Anyone aware of any issues on Travis with working directory? I am seeing this error on Travis but cannot reproduce locally: https://travis-ci.org/rstudio/tfestimators/builds/268732994#L1347

Re-opening this issue to track.
