### ISSUE TITLE
Upstream Changes

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#40]
List of upstream changes that require changes to our R API. I am keeping the list here as TODOs.

**Comment by terrytangyuan** [comment]
`contrib.estimator`:
https://github.com/tensorflow/tensorflow/pull/12867/commits/384337f6fa76ae37e7472f47362d880248c379d1

**Comment by terrytangyuan** [comment]
API change:
New `yield_single_examples` parameter for `predict()`: https://github.com/tensorflow/tensorflow/pull/16991/commits/f3ebb0b165563192bd80f5dd34a04cd0ac37ff6f

**Comment by terrytangyuan** [comment]
Warm start utilities: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/warm_starting_util.py

**Comment by terrytangyuan** [comment]
@jjallaire  `BoostedTreesClassifier` and `BoostedTreesRegressor` are now indeed available in core [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/canned/boosted_trees.py): 

Also `estimator.WarmStartSettings` was presented during summit as well that can be used for linear/DNN estimators, which is worth looking into as well.

**Comment by jjallaire** [comment]
Oh that's great! @kevinykuo What would you think about adding `boosted_trees_classifier()` and `boosted_trees_regressor()` to the package?

**Comment by kevinykuo** [comment]
I'll take a look. Would be interesting to see how this compares to h2o/h2o4gpu. @terrytangyuan are there existing benchmarks yet?

**Comment by terrytangyuan** [comment]
Not yet. But I know that @szilard is working on benchmarking h2o4gpu in https://github.com/szilard/benchm-ml. Perhaps we can coordinate once we have those tree estimators in.

**Comment by szilard** [comment]
h2o4gpu for GBMs is essentially xgboost on GPU (well, the R API h2o4gpu still needs to add support for sparse matrices (waiting for reticulate for that) to be as fast as xgboost).

Anyway, I have an minimal benchmark of what I think are the most widely used and best performing GBM implementations here (CPU and GPU): https://github.com/szilard/GBM-perf though I'm using only 1 dataset, a major drawback - I have a wishlist:
<img width="776" alt="screen shot 2018-04-02 at 11 32 42 am" src="https://user-images.githubusercontent.com/844827/38209567-9dd4a586-3669-11e8-9af8-f971e3ccdf8a.png">

When I looked at boosting in TF last time, the API seemed very unfriendly for categorical data and my guess was/is that the TF architecture is probably not very good for fast GBMs. Maybe I should check again?

**Comment by terrytangyuan** [comment]
@szilard Thanks. Yea there's now a boosted tree based on TF Estimators API which should be more friendly now. @kevinykuo is working on adding that to the R API (this repo). We'll keep you posted once it's usable.

**Comment by szilard** [comment]
I could try out the Python API actually. Btw I wonder if TF GB supports sparse matrices. When you have  categorical data (i.e. almost always for business problems/data) you can get even 10x faster in speed and 10x lower on memory usage if you deal directly with cats (e.g. lightgbm) or you do the 1-hot encoding with sparse matrices (e.g. xgboost).

**Comment by terrytangyuan** [comment]
@szilard Yes, theoretically you can provide sparse tensors inside the input function (see [this section](https://www.tensorflow.org/programmers_guide/estimators#structure_of_a_pre-made_estimators_program))but I've never tried it before. Feel free to try it out and report any issues to TensorFlow and someone there will help out. Right now you can find some examples of TFBT in the test [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/canned/boosted_trees_test.py).
