### ISSUE TITLE
enhanced name scopes for tidyselect

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tfestimators#42]
We current establish the name scope for tidyselect via the first argument to `feature_columns()`, e.g.

```r
fc <- feature_columns(mtcars,
  column_numeric(disp),
  column_numeric(cyl)
)
```

This works fine for simple cases, however in some cases you actually need to create named variables which map to the feature columns (so that you can create embeddings). For example, consider this code:

```r
# Categorical base columns
education <- column_categorical_with_hash_bucket("education", hash_bucket_size = 1000L, dtype = tf$int32)
relationship <- column_categorical_with_hash_bucket("relationship", hash_bucket_size = 100L, dtype = tf$int32)
workclass <- column_categorical_with_hash_bucket("workclass", hash_bucket_size = 100L, dtype = tf$int32)
occupation <- column_categorical_with_hash_bucket("occupation", hash_bucket_size = 100L, dtype = tf$int32)
native_country <- column_categorical_with_hash_bucket("native_country", hash_bucket_size = 1000L, dtype = tf$int32)

# Continuous base columns.
age <- column_numeric("age")
age_buckets <- column_bucketized(age, boundaries = list(18, 25, 30, 35, 40, 45, 50, 55, 60, 65))
education_num <- column_numeric("education_num")
capital_gain <- column_numeric("capital_gain")
capital_loss <- column_numeric("capital_loss")
hours_per_week <- column_numeric("hours_per_week")

#' ### Define Wide and Deep Columns

wide_columns <- list(native_country, education, occupation, workclass, relationship, age_buckets)

deep_columns <- list(
  column_embedding(workclass, dimension = 8L),
  column_embedding(education, dimension = 8L),
  column_embedding(relationship, dimension = 8L),
  column_embedding(native_country, dimension = 8L),
  column_embedding(occupation, dimension = 8L),
  age, education_num, capital_gain, capital_loss, hours_per_week)

#' ### Combining Wide and Deep Models into One

model <- linear_dnn_combined_classifier(
  linear_feature_columns = wide_columns,
  dnn_feature_columns = deep_columns,
  dnn_hidden_units = c(100L, 50L)
)
```

Here we are forced back into the use of strings for referring to columns (because we need to create addressable R objects for subsequent calls to `column_embedding()`.

I think this re-raises the issue of how the current tidyselect "scope" is established. It would be very nice to be able to somehow set it globally so that instances like the above could use tidyselect as well as so that you can write arbitrary R code to build up feature columns (it seems likely that *just* relying on pattern matching won't be enough to capture all cases, especially when hyper-parameters drive which columns are included). 

A couple of possibilities:

```r
active_feature_columns(mtcars)
cyl <- column_numeric(cyl)
disp <- column_numeric(disp)
```

```r
with_columns(mtcars, {
   cyl <- column_numeric(cyl)
   disp <- column_numeric(disp)
})
```

Note that our current syntax is really just another (less flexible) way of expressing the latter (scoped availability of active feature columns):

```r
feature_columns(mtcars,
   column_numeric(cyl),
   column_numeric(disp)
)
```

Except that our current syntax is only capable of producing an R list and can't handle any imperative code.

@hadley, @terrytangyuan, and @kevinushey what do you think the of the `with_columns` syntax?

**Comment by terrytangyuan** [comment]
I think we already have this now, right? @jjallaire

**Comment by jjallaire** [comment]
Indeed we do!

On Thu, Aug 31, 2017 at 5:43 PM, Yuan (Terry) Tang <notifications@github.com

**Comment by terrytangyuan** [comment]
Great! Closing this now.
