### ISSUE TITLE
Rewrite examples in R

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#46]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/learn

**Comment by terrytangyuan** [comment]
Check out this folder for officially supported/maintained/tested examples using estimators: https://github.com/tensorflow/models/tree/master/official.

**Comment by eddelbuettel** [comment]
Any progress?  I started noodling with a first example from .py to .R but didn't get too far yet.

**Comment by terrytangyuan** [comment]
@eddelbuettel No progress on this at least from my end. It would be very nice to rewrite those TF Estimators official tutorials in R.
