### ISSUE TITLE
'predict()' should marshal return values into nicer data structures when appropriate

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tfestimators#49]
For example, given this code:

```R
# define feature columns
  .feature_columns <- feature_columns(
    cyl = column_numeric("cyl"),
    drat = column_numeric("drat")
  )
  
  .input_fn <- input_fn(
    mtcars,
    response = "mpg",
    features = names(columns)
  )
  
  # try fitting a linear regression model with tfestimators
  tf_model <-
    linear_regressor(feature_columns = unname(.feature_columns)) %>%
    train(input_fn = .input_fn)
  
  predict(tf_model, input_fn = .input_fn)
```

The output is of the form:

```R
> predict(tf_model, input_fn = .input_fn) %>% str()
List of 32
 $ :List of 1
  ..$ predictions: num [1(1d)] 4.99
 $ :List of 1
  ..$ predictions: num [1(1d)] 4.23
< ... >
```

Compare this to base R, where you receive a named numeric vector:

```
> model <- lm(mpg ~ cyl + drat, data = mtcars)
>   predict(model) %>% str()
 Named num [1:32] 21.1 21.1 26 19.6 14.8 ...
 - attr(*, "names")= chr [1:32] "Mazda RX4" "Mazda RX4 Wag" "Datsun 710" "Hornet 4 Drive" ...
```

**Comment by jjallaire** [comment]
If we don't want to change the return value of predict (which given the discussion in this thread is certainly a reasonable position) I think we need a suite of functions that can clean up predict output from canned estimators for easy inspection and visualization. Every internal user that has tried to use tfestimators runs into the issue of predict output immediately and ends up hand rolling a solution.

Alternatively, we could have `predict(..., as_list = FALSE)` and in the case of `as_list = FALSE` the default have a per-estimator-type transform/cleaner function that runs. That way the "out of the box" experience yields the kind of data structures R users expect and can easily visualization but at the same time we document that passing `as_list = TRUE` gives you the unfiltered output from predict.

@kevinushey @terrytangyuan @edgararuiz Could you imagine easily what `as_list = FALSE` might yield for some of the canned estimators?

**Comment by terrytangyuan** [comment]
Yeah I totally agree. 

For example, the following (just fixed one thing at HEAD so please pull):
```
specs <- mtcars_classification_specs() # from testthat/helper-utils.R
  clf <-
    dnn_linear_combined_classifier(
      linear_feature_columns = specs$linear_feature_columns,
      dnn_feature_columns = specs$dnn_feature_columns,
      dnn_hidden_units = c(3L, 3L),
      dnn_optimizer = "Adagrad"
    ) %>% train(input_fn = specs$input_fn)
predictions <- predict(clf, input_fn = specs$input_fn, predict_keys = list("classes", "probabilities"))
```
would give you a list of items where each item looks like this:
```
[[32]]
[[32]]$probabilities
[1] 0.5061268 0.4938732

[[32]]$classes
[1] "0"
```
So it looks pretty easy to wrap the results from the existing canned estimators - linear and dnn. 

What I am uncertain about is prediction output of the time series estimators (in contrib) that I am helping to move to core. But it's going to be a while until those are available. We'll worry about those later.

I also think that we should expose the wrapper function that cleans the predictions so users of custom estimator may want to use this sometimes as well if the format of their predictions is simple (guess 70% of the time since in most of the cases users will be only playing with different layers instead of the prediction format).

**Comment by jjallaire** [comment]
How about we add a `simplify` argument (sort of like the apply family of R functions) and have it default to "auto". We could always simplify things that are clearly simple vector data and do some other auto-simplification for canned estimators. If in the process of doing this we develop some functions of more general applicability we can export them.

**Comment by jjallaire** [comment]
Here is a more formal proposal:

- `predict(..., simplify = TRUE)` by default. `simplify` can be either `TRUE` (simplify if possible), `FALSE` (never simplify) or a custom function that takes a list and performs a simplification.

- We implement simplifiers for all of the canned estimators for which this is practical

- We provide a hook for custom estimators to provide a simplifier (perhaps this is attached to model_fn, perhaps via an S3 method)

- We export any relevant helper functions used in simplification (we may or may not have good candidates for this, just something to consider).

@terrytangyuan Could you take a crack at this as a PR?

**Comment by terrytangyuan** [comment]
Thanks for the detailed proposal! Yes, I'll tackle this soon!
