### ISSUE TITLE
provide 'plot()' methods for estimator objects

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tfestimators#54]
We should try to provide a plot method for `tf_estimator` objects, for simple model diagnostics / inspecting the state + history of the model.

Example from @jjallaire with Keras:

![](https://user-images.githubusercontent.com/104391/28115775-3fd583ca-66d4-11e7-8de5-c624e977e5ed.png)

And example of what R produces (not advocating we try to re-produce those plots with Keras; just doing this to add context on what R users might like to see immediately after generating a plot)

![plot](https://user-images.githubusercontent.com/1976582/28330434-6ae9f28a-6ba2-11e7-97c9-c170e244aeb5.png)

Overarching point is that users should be able to call `plot(estimator)` to immediately get some visual feedback on the state of their estimator.

**Comment by terrytangyuan** [comment]
Is this still necessary? I felt like tfruns already provided this.

**Comment by jjallaire** [comment]
Agreed. I think we are all set here.

On Wed, Sep 27, 2017 at 9:03 PM, Yuan (Terry) Tang <notifications@github.com

**Comment by terrytangyuan** [comment]
Sounds good!
