### ISSUE TITLE
deal with dplyr masking caused by re-export of tidyselect functions

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tfestimators#73]
This code:

```r
library(tfestimators)
library(dplyr)
```

Result in this masking warning when loading dplyr:

```
Attaching package: ‘dplyr’

The following objects are masked from ‘package:tfestimators’:

    contains, ends_with, everything, matches, one_of, starts_with
```

Obviously once dplyr imports tidyselect and that version of dplyr is on CRAN this problem will go away, but the dev version of dplyr does not yet depend on tidyselect so it seems unlikely that this change will make it to CRAN soon.

I think we need to deal with this before publicizing tfestimators as I'm sure people will want to use the two packages together.  

Since we only use `vars_select` in a couple of places (https://github.com/rstudio/tfestimators/search?utf8=%E2%9C%93&q=vars_select&type=) it seems like one solution might be to do the evaluation of `vars_select` in a special environment that has access to the tidyselect filtering functions. That way we wouldn't need to do these re-exports: https://github.com/rstudio/tfestimators/blob/master/R/reexports.R#L26-L42 and the search path conflicts would go away.

@hadley @lionel- Let us know what you think.

**Comment by jjallaire** [comment]
I think we need to resolve this issue before we publicize the new TF site during the first week of September. 

@hadley The issue we have here is that if users attempt to use dplyr and tfestimators together then masking occurs. I think that once dplyr depends on tidyselect this issue will go away but I'm not sure how far off that is. One thought we have for a workaround is to not re-export the tidyselect predicate functions and instead evaluate them in a special environment, but it's not 100% clear how to do that correctly.

**Comment by kevinushey** [comment]
I'm fairly confident I know how to tackle this so I'll take a shot tomorrow.

**Comment by kevinushey** [comment]
Looks like I actually did tackle this one already! The following works fine with or without `tidyselect` explicitly attached:

```R
library(tfestimators)

vars <- c("a1", "a2", "a3")
feature_columns(
  column_numeric(starts_with("a")),
  names = vars
)
```

**Comment by kevinushey** [comment]
Note that the tidyselect helpers are only made available within the context of a `feature_columns` call. Are there any other contexts where we might want to handle this?

**Comment by jjallaire** [comment]
Okay, that's great to hear!

We also use tidyselect within input_fn

**Comment by kevinushey** [comment]
Thanks! This should be handled correctly there now as well.
