### ISSUE TITLE
training progress treatment

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tfestimators#74]
Where did we end up in terms of having a progress bar treatment for training? I believe that there is a built in RunHook for this but I'm not positive. If there is nothing built-in it's possible we could borrow the progress bar implementation already contained in Keras.

**Comment by kevinushey** [comment]
I'm declaring defeat on this one. As far as I can see, there is no way to effectively produce metrics during training.

**Comment by jjallaire** [comment]
Okay, glad we tried in any case. We can talk to the TF team about this when
we see them in Sept.
