### ISSUE TITLE
re-visit feature columns specification?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tfestimators#78]
I'd like to propose a re-working of the syntax we use for feature column definitions. Currently, feature columns are defined as e.g.

```R
cols <- feature_columns(
  column_numeric(starts_with("a")),
  column_numeric("cyl")
)
```

It feels to me that we could try to express this in a more 'pattern-matching' way, e.g.

```R
cols <- feature_columns(
    starts_with("a") ~ column_numeric(dtype = tf$float32),
    "cyl"            ~ column_numeric(dtype = tf$float32)
)
```

This feels a bit cleaner as it separates the 'condition' from the 'object constructed from that condition'. We could also mix in plain, non-formula objects in the call e.g.

```R
cols <- feature_columns(
    starts_with("a") ~ column_numeric(dtype = tf$float32),
    "cyl"            ~ column_numeric(dtype = tf$float32),
    c("a1", "a2")    ~ column_crossed()
    column_numeric("other"),
)
```

What do you think @jjallaire @terrytangyuan?

**Comment by terrytangyuan** [comment]
I am okay with this addition. I am just a bit confused on why this would help. I feel like this requires additional typing and formatting to get the indentation + ~ look right.

**Comment by jjallaire** [comment]
I'm not sure as I haven't seen that syntax elsewhere in R and I'm not sure how it dovetails with other pattern matching schemes (if any) in R. My biggest issue with it is that I think the simple case is much clearer with the existing syntax:

```r
column_numeric("foo")
```

vs. 

```r
"foo" ~ column_numeric
```

I think that we enough new interlocking concepts in the API to learn that if we throw this syntax at people it might make the whole thing feel too foreign.

**Comment by kevinushey** [comment]
FWIW this syntax is already used in a couple places in the R universe:

1. `dplyr::case_when()`:

```R
x <- 1:50
case_when(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  TRUE ~ as.character(x)
)
```

2. `purrr::when()`:

```R
1:10 %>%
  when(
    sum(.) <=  50 ~ sum(.),
    sum(.) <= 100 ~ sum(.)/2,
    ~ 0
  )
```

So it's not entirely novel / foreign.

**Comment by terrytangyuan** [comment]
Cool. Just curious - what was the motivation behind creating that syntax? What usecases can it support in additional to what we already supported?

**Comment by kevinushey** [comment]
It's purely stylistic: it does not enable anything new.

**Comment by jjallaire** [comment]
I'd be okay with supporting it as a syntactic option, but I don't want to
lose the simple and familiar column_numeric("foo") syntax that we already
have. Not sure if there is a clean way to make it optional though.

**Comment by terrytangyuan** [comment]
Yeah I am okay with it too as long as we teach users the simpler way first and in most examples.

**Comment by kevinushey** [comment]
Right, I'm definitely not advocating replacing the old syntax; just advocating this as an alternative way of specifying feature columns. There shouldn't be any reason why we can't support both.

**Comment by kevinushey** [comment]
Implemented with https://github.com/rstudio/tfestimators/commit/abfd1c59faeb733f2fc6ac375f2c93fdbf483a30.
