### ISSUE TITLE
TensorBoard stuck

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#79]
This seems to happen to both custom and canned estimator. This command just keeps hanging there and tensorboard is not launched in the browser:
```
> tensorboard(log_dir = tmp_dir, launch_browser = TRUE)
W0826 12:26:31.143542 Reloader event_accumulator.py:303] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0826 12:26:31.144389 Reloader event_accumulator.py:311] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
```
@jjallaire @kevinushey are you aware of any recent changes that might break this?

**Comment by jjallaire** [comment]
Try installing the tensorflow package from GitHub (we had to make a change
as a result in some new behavior in TF v1.3)

**Comment by kevinushey** [comment]
You can try running devtools::install_deps() to quickly update all package dependencies in the project as well.

**Comment by terrytangyuan** [comment]
Bumping tensorflow version to 1.3.0.9005 worked! Thanks!
