### ISSUE TITLE
Handle situation where input is exhausted earlier

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#80]
This is due to a large batch size specified in the input_fn. Perhaps we should generate an warning that the data is exhausted before reaching the 20th step:
```
  specs <- mtcars_regression_specs()

  estimator <- dnn_linear_combined_regressor(
    linear_feature_columns = specs$linear_feature_columns,
    dnn_feature_columns = specs$dnn_feature_columns,
    dnn_hidden_units = c(1L, 1L),
    dnn_optimizer = "Adagrad"
  )
  
  train(estimator, input_fn = specs$input_fn, steps = 20)
```
Otherwise, the visualization seems weird to the user:

![image](https://user-images.githubusercontent.com/4269898/29743464-c54f1c78-8a60-11e7-8177-5a0dabce0837.png)

BTW, @jjallaire the Y-axis label is still looking strange. Which version of tfruns should include the fix for that?

**Comment by kevinushey** [comment]
This should be fixed now as well, although the graph does look odd when there are only 2 steps. (However, there's not really a good way around that anyhow)
