### ISSUE TITLE
Properly handle case where `steps = NULL` for visualization

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#81]
Currently, when `steps = NULL` which is the default for `train()`. The `hook_view_metrics` will break.

**Comment by terrytangyuan** [comment]
I pushed this commit to handle this - only pad when steps is not `NULL`. However, I am seeing something strange. 

When I ran the training for this example: https://github.com/rstudio/tfestimators/blob/master/vignettes/examples/custom_estimator.R

I got visualization like this:
![image](https://user-images.githubusercontent.com/4269898/29743647-27f23632-8a64-11e7-8900-7fb515090f5a.png)

However, when I click "zoom" in RStudio, it becomes this:
![image](https://user-images.githubusercontent.com/4269898/29743660-5606257e-8a64-11e7-93e2-26808a2fb08c.png)

**Comment by terrytangyuan** [comment]
What about the zoom issue that I mentioned here? Is that fixed too?

**Comment by kevinushey** [comment]
Yes, that should be fixed as well.

**Comment by terrytangyuan** [comment]
Great!
