### ISSUE TITLE
'column_categorical_with_identity()' requires default argument?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tfestimators#85]
E.g. I'm seeing:

```R
> cols <- feature_columns(
+   column_numeric("profit"),
+   column_categorical_with_identity("profession", num_buckets = 5L)
+ )
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: default_value [] not in range [0, 5), column_name profession
```

The function signature:

```R
> column_categorical_with_identity
function(..., num_buckets, default_value = NULL) { ... }
```

@terrytangyuan should `default_value` be using e.g. `0` as the default value here?

**Comment by terrytangyuan** [comment]
Which dataset is this?

**Comment by kevinushey** [comment]
There is no data set associated. Just attempting to construct the feature column is failing.

**Comment by terrytangyuan** [comment]
Oh I see your point now. I think in this case switching to 0 is indeed more user-friendly.

**Comment by terrytangyuan** [comment]
The issue is right now our feature columns wrapper is associated with the dataset. For the Python API, it's more lazily evaluated, e.g. this works in Python:
```
from tensorflow.python.feature_column import feature_column_lib as fc
column = fc.categorical_column_with_identity('profession', num_buckets=5)
```

**Comment by terrytangyuan** [comment]
Should be fixed in head.
