### ISSUE TITLE
status of experiments?

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tfestimators#86]
Were we going to remove experiment from the public API for this release? I recall that there were issues leading us to say that it's use wasn't recommended, and that this resulted in a decision to remove it until TF v1.4.

If this is the intention then we should un-export the function(s) and remove the vignette and all references to it.

**Comment by terrytangyuan** [comment]
Yes I thought I removed the API from namespace as well as the tutorial. I probably forgot to remove the mentions of it in other tutorials.

**Comment by jjallaire** [comment]
It's still in the NAMESPACE.

On Thu, Aug 31, 2017 at 9:42 AM, Yuan (Terry) Tang <notifications@github.com

**Comment by terrytangyuan** [comment]
Oh I missed the generic method. I will remove it.

**Comment by kevinushey** [comment]
https://github.com/rstudio/tfestimators/commit/5c2e8b4113f86079108cf5695f1bda9783a06476

**Comment by terrytangyuan** [comment]
Thanks Kevin! I wasn't able to do it during work hours unfortunately.

**Comment by kevinushey** [comment]
No worries!
