### ISSUE TITLE
fix roxygen issues

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tfestimators#88]
Noted this when I run devtools::document:

<img width="593" alt="screen shot 2017-08-31 at 7 55 53 am" src="https://user-images.githubusercontent.com/104391/29922037-0337a5ae-8e22-11e7-8b5f-fd3b4160ea92.png">

Let's make sure those help topics have titles.

Also it looks like one of us is running the dev version of roxygen. If practical let's roll back to the CRAN version (or have all of us roll up to the dev version if that's actually required).

**Comment by terrytangyuan** [comment]
Agreed. I'd prefer CRAN version unless it's required.

**Comment by kevinushey** [comment]
Just made the change to enforce usage of CRAN roxygen2. The other warnings here can actually be ignored -- I'm using those blocks to provide parameter documentation that can be shared across multiple function definitions.

For example, we define parameter documentation for estimators here:

https://github.com/rstudio/tfestimators/blob/1748564a3ccc0adad6978700cc70394ce3335a1f/R/estimators.R#L1-L41

and then we inherit this documentation at e.g.

https://github.com/rstudio/tfestimators/blob/1748564a3ccc0adad6978700cc70394ce3335a1f/R/dnn_estimators.R#L5

https://github.com/rstudio/tfestimators/blob/1748564a3ccc0adad6978700cc70394ce3335a1f/R/dnn_linear_combined_estimators.R#L6

This allows us to avoid unnecessary divergence in documentation across identical parameters used in different functions.

@hadley is planning to promote this (or a different form of this) to a first-class feature in the next version of `roxygen2` so I think we're okay to stick with this scheme (we can just ignore the warnings during documentation building).

**Comment by jjallaire** [comment]
Okay, sounds good!
