### ISSUE TITLE
`crossed_columns` assume a `key` attribute, but some objects do not have this attribute

### ISSUE THREAD

**Issue by dominiqueemmanuel** [rstudio/tfestimators#96]
Firstly I would like to thank you for all the great works in this package!

This issue concerns (or appears in) the [example wide and deep](https://github.com/rstudio/tfestimators/blob/master/vignettes/examples/wide_and_deep.R).

I run everything in the example, but the instruction produces an error:
```
crossed_columns <- feature_columns(
  native_country, education, occupation, workclass, relationship, age_buckets,
  column_crossed(c("education", "occupation"), hash_bucket_size = 10000),
  column_crossed(c("native_country", "occupation"), hash_bucket_size = 10000),
  column_crossed(c(age_buckets, "education", "occupation"), hash_bucket_size = 10000)
)
#Error in py_get_attr_impl(x, name, silent) : 
#  AttributeError: '_BucketizedColumn' object has no attribute 'key'
```

The function `crossed_columns` seems to manage objects with a `key` attribute (I guess it from the meaning of the error and the [source code](https://github.com/rstudio/tfestimators/blob/4c4c1798fa8d9f84fcddd69513c30e83dbb0f8bb/R/feature_columns.R#L52)) , but this is not the case of `age_buckets` (nor `column_crossed(c("education", "occupation"), hash_bucket_size = 10000)`, `  column_crossed(c("native_country", "occupation"), hash_bucket_size = 10000)` and `column_crossed(c(age_buckets, "education", "occupation"), hash_bucket_size = 10000)` which have a `keys` attributes but not a `key` attribute).

For infromation:
```
sessionInfo()
# R version 3.4.1 (2017-06-30)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 7 x64 (build 7601) Service Pack 1
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
# [3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
# [5] LC_TIME=French_France.1252    
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
#   [1] tfestimators_0.1.2.9000
# 
# loaded via a namespace (and not attached):
#   [1] Rcpp_0.12.13          dplyr_0.7.2           assertthat_0.2.0     
# [4] R6_2.2.2              jsonlite_1.5          magrittr_1.5         
# [7] tfruns_0.9.1          rlang_0.1.2           curl_2.8.1           
# [10] bindrcpp_0.2          reticulate_1.2        tools_3.4.1          
# [13] glue_1.1.1            purrr_0.2.3           compiler_3.4.1       
# [16] pkgconfig_2.0.1       tensorflow_1.4        bindr_0.1            
# [19] tidyselect_0.2.0.9000 tibble_1.3.4  



reticulate::py_config()
# python:         C:\Users\Dominique\Anaconda3\envs\r-tensorflow\python.exe
# libpython:      C:/Users/Dominique/Anaconda3/envs/r-tensorflow/python36.dll
# pythonhome:     C:\Users\DOMINI~1\ANACON~1\envs\R-TENS~1
# version:        3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
# Architecture:   64bit
# numpy:          C:\Users\DOMINI~1\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
# numpy_version:  1.13.3
# tensorflow:     C:\Users\DOMINI~1\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow
# 
# python versions found: 
#   C:\Users\Dominique\Anaconda3\envs\r-tensorflow\python.exe
# C:\Users\DOMINI~1\ANACON~1\python.exe
```
Thanks a lot
Dom

**Comment by terrytangyuan** [comment]
@jjallaire @kevinushey Could you take a look at this issue? @dominiqueemmanuel What is the result of your `tensorflow::tf_config()`?

**Comment by dominiqueemmanuel** [comment]
Here is the corresponding result:
```
tensorflow::tf_config()
# TensorFlow v1.3.0 (C:\Users\DOMINI~1\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow)
# Python v3.6 (C:\Users\Dominique\Anaconda3\envs\r-tensorflow\python.exe)
```

**Comment by jjallaire** [comment]
@kevinushey Maybe we just need to ammend this commit (https://github.com/rstudio/tfestimators/commit/abfd1c59faeb733f2fc6ac375f2c93fdbf483a30) to look for both `key` and `keys`?

**Comment by jjallaire** [comment]
Note that any fix now needs to go onto the v1.3.0 branch which we can then merge into master.

**Comment by terrytangyuan** [comment]
@jjallaire Just created v1.3.0 branch and deleted v1.3.0 tag. Could you make that branch protected in addition to master branch?

**Comment by kevinushey** [comment]
The intention of that bit of code is to eliminate duplicated columns (e.g. if a column happened to be captured by multiple `tidyselect` criteria). Perhaps a better solution is to shrink the set of available columns as they get matched, rather than cleaning up at the end?

**Comment by jjallaire** [comment]
This issue should now be resolved so I'll close (feel free to re-open if you still see problems on your end)
